/* Print the search tables as Ripes assembler data.
 *
 * The tables are the same ones ida.c builds on the host: the factored
 * quarter-turn transitions, one block per face, and the two pattern
 * databases. Ripes has no .rodata directive, so they go in .data; the
 * half-word tables come first so every .half stays 2-byte aligned
 * (each half-word block is an even number of bytes).
 */
#define IDA_NO_MAIN
#include "ida.c"

static void emit_half(const char *label, const uint16_t *v, int n)
{
    printf("%s:\n", label);
    for (int i = 0; i < n; ++i)
        printf("%s%u%s", i % 16 ? ", " : "        .half ", v[i],
               i % 16 == 15 || i == n - 1 ? "\n" : "");
}

static void emit_byte(const char *label, const uint8_t *v, int n)
{
    printf("%s:\n", label);
    for (int i = 0; i < n; ++i)
        printf("%s%u%s", i % 16 ? ", " : "        .byte ", v[i],
               i % 16 == 15 || i == n - 1 ? "\n" : "");
}

int main(void)
{
    static const char *const face[3] = {"R", "B", "D"};
    char label[32];

    build_transitions();
    build_perm_pdb();
    build_orient_pdb();

    printf("# Generated by gen_tables.c; do not edit by hand.\n");
    printf("# %d bytes of tables.\n",
           3 * (PERMUTATIONS + ORIENTATIONS) * 2 + PERMUTATIONS + ORIENTATIONS);
    /* The data before the tables (the input string, perm[]) can leave
     * the location counter odd; .align 2 rounds it up to 4 bytes. */
    printf("        .data\n        .align 2\n");
    for (int f = 0; f < 3; ++f) {
        snprintf(label, sizeof label, "perm_%s", face[f]);
        emit_half(label, perm_move[f], PERMUTATIONS);
    }
    for (int f = 0; f < 3; ++f) {
        snprintf(label, sizeof label, "orient_%s", face[f]);
        emit_half(label, orient_move[f], ORIENTATIONS);
    }
    emit_byte("perm_pdb", perm_pdb, PERMUTATIONS);
    emit_byte("orient_pdb", orient_pdb, ORIENTATIONS);
    /* Base address of each face's block, so the search can find a table
     * by indexing with the face instead of multiplying by the block size.
     * Ripes resolves a label in .word only if it is already defined, so
     * these have to come after the tables. */
    printf("        .align 2\n");
    printf("perm_base:\n        .word perm_R, perm_B, perm_D\n");
    printf("orient_base:\n        .word orient_R, orient_B, orient_D\n");
    return 0;
}
