/* Freestanding C version of the algorithm in rubik.s.
 *
 * This is the reference build the assembly is compared against: compiled
 * with riscv64-unknown-elf-gcc -O2 -march=rv32i -mabi=ilp32 and run in
 * Ripes. It does the same work in the same order as rubik.s: parse and rank
 * the input, IDA* over max(permutation PDB, orientation PDB) with each
 * face's three turns generated by turning the previous child once more,
 * then replay and print the path, checking it reaches solved and has the
 * expected length. There is no C library in Ripes, so output and exit go
 * through ecall, and _start below is the entry point.
 */
#include <stdint.h>

#include "build/tables.h"

static const char input[15] = "21345671111111";
static const unsigned expected = 11;

static void put_char(int c)
{
    register int a0 __asm__("a0") = c;
    register int a7 __asm__("a7") = 11;          /* PrintChar */
    __asm__ volatile("ecall" : : "r"(a0), "r"(a7));
}

struct frame {
    uint16_t p, o;       /* the state at this depth */
    uint16_t cp, co;     /* the child being turned */
    uint8_t face, turn;  /* face 0..2 (3 = done), quarter turns applied */
};

static struct frame frames[12];

static unsigned h(unsigned p, unsigned o)
{
    unsigned a = perm_pdb[p], b = orient_pdb[o];
    return a > b ? a : b;
}

/* Skip the face of the move that led to depth d. */
static void skip_last(int d)
{
    if (d > 0 && frames[d - 1].face == frames[d].face)
        frames[d].face++;
}

static void enter(int d)
{
    struct frame *f = &frames[d];
    f->cp = f->p;
    f->co = f->o;
    f->face = 0;
    f->turn = 0;
    skip_last(d);
}

int main(void)
{
    uint8_t perm[7];
    unsigned seen = 0, sum = 0, p = 0, o = 0;

    for (int i = 0; i < 7; ++i) {
        unsigned c = (unsigned) (input[i] - '1');
        if (c > 6 || (seen >> c) & 1)
            return 2;
        seen |= 1u << c;
        perm[i] = (uint8_t) c;
    }
    for (int i = 0; i < 7; ++i) {
        unsigned t = (unsigned) (input[7 + i] - '1');
        if (t > 2)
            return 2;
        sum += t;
        if (i < 6)
            o = o + o + o + t;
    }
    while (sum >= 3)
        sum -= 3;
    if (sum)
        return 2;
    for (int i = 0; i < 7; ++i) {
        unsigned c = 0, q = p;
        for (int j = i + 1; j < 7; ++j)
            c += perm[j] < perm[i];
        /* p *= 7 - i by repeated addition, as rubik.s does. Left alone, gcc
         * turns this loop back into a multiply and calls __mulsi3, which the
         * assignment forbids; the empty asm hides p from that rewrite. */
        for (int k = 7 - i; k > 1; --k) {
            p += q;
            __asm__("" : "+r"(p));
        }
        p += c;
    }

    int d;
    for (unsigned bound = h(p, o);; ++bound) {
        d = 0;
        frames[0].p = (uint16_t) p;
        frames[0].o = (uint16_t) o;
        enter(0);
    check:
        if (frames[d].p == 0 && frames[d].o == 0)
            goto found;
    next:
        {
            struct frame *f = &frames[d];
            if (f->turn == 3) {
                f->face++;
                f->turn = 0;
                f->cp = f->p;
                f->co = f->o;
                skip_last(d);
            }
            if (f->face == 3) {
                if (--d >= 0)
                    goto next;
                continue;  /* the whole tree failed: raise the bound */
            }
            f->cp = perm_move[f->face][f->cp];
            f->co = orient_move[f->face][f->co];
            f->turn++;
            if ((unsigned) d + 1 + h(f->cp, f->co) > bound)
                goto next;
            frames[d + 1].p = f->cp;
            frames[d + 1].o = f->co;
            enter(++d);
            goto check;
        }
    }

found:
    for (int i = 0; i < d; ++i) {
        const struct frame *f = &frames[i];
        for (unsigned t = 0; t < f->turn; ++t) {
            p = perm_move[f->face][p];
            o = orient_move[f->face][o];
        }
        put_char("RBD"[f->face]);
        if (f->turn > 1)
            put_char(f->turn == 2 ? '2' : '\'');
        put_char(' ');
    }
    if (p || o)
        return 1;  /* T5: the path must reach solved */
    if ((unsigned) d != expected)
        return 3;
    put_char('\n');
    return 0;
}

/* Entry point: no C runtime, so call main and exit with its return value. */
__attribute__((naked, section(".text.start"))) void _start(void)
{
    __asm__ volatile("call main\n\t"
                     "li a7, 93\n\t"  /* Exit with status a0 */
                     "ecall");
}
